# 🐼 Pandas Class 7 Assignment
## Merging, Joining & Concatenation

### Level: Easy → Intermediate

**Topics:** `pd.concat()` • `merge()` • `inner/left/right/outer` joins • `left_on/right_on` • `join()` • index alignment • missing values

### Instructions
- Do **not** load any CSV file.
- Create the DataFrames given in the questions.
- Solve every question in the blank code cell.
- Use the Expected Output to check your answer.


# Assignment Questions

### Q1. Create two DataFrames `df1` and `df2` with columns `ID`, `Name`, `Marks`. df1 has Aman/Neha/Ravi and df2 has Priya/Karan/Simran.

**Expected Output: Two DataFrames with 3 rows each.**

In [ ]:
# Write your answer here
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Aman', 'Neha', 'Ravi'],
    'Marks': [85, 90, 78]
})

df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['Priya', 'Karan', 'Simran'],
    'Marks': [88, 92, 81]
})

print(df1)
print(df2)

   ID  Name  Marks
0   1  Aman     85
1   2  Neha     90
2   3  Ravi     78
   ID    Name  Marks
0   4   Priya     88
1   5   Karan     92
2   6  Simran     81


### Q2. Use `pd.concat()` to combine `df1` and `df2` vertically.

**Expected Output: One DataFrame with 6 rows.**

In [ ]:
# Write your answer here
pd.concat([df1, df2])

,ID,Name,Marks
0,1,Aman,85
1,2,Neha,90
2,3,Ravi,78
0,4,Priya,88
1,5,Karan,92
2,6,Simran,81


### Q3. Repeat the concatenation using `ignore_index=True`.

**Expected Output: Index becomes 0 to 5.**

In [ ]:
# Write your answer here
pd.concat([df1, df2], ignore_index=True )

,ID,Name,Marks
0,1,Aman,85
1,2,Neha,90
2,3,Ravi,78
3,4,Priya,88
4,5,Karan,92
5,6,Simran,81


### Q4. Create `df3 = pd.DataFrame({'City':['Delhi','Mumbai','Pune']})` and concatenate it horizontally with `df1` using `axis=1`.

**Expected Output: df1 gets a City column.**

In [ ]:
# Write your answer here
df3 = pd.DataFrame({'City':['Delhi','Mumbai','Pune']})

pd.concat([df1, df3], axis = 1)

,ID,Name,Marks,City
0,1,Aman,85,Delhi
1,2,Neha,90,Mumbai
2,3,Ravi,78,Pune


### Q5. Create two small DataFrames with the same index but different columns and combine them horizontally using `pd.concat(axis=1)`.

**Expected Output: Columns from both DataFrames appear side by side.**

In [ ]:
# Write your answer here
df1 = pd.DataFrame({
    'Name': ['Aman', 'Neha', 'Ravi']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'Marks': [85, 90, 78]
}, index=[1, 2, 3])

pd.concat([df1, df2], axis = 1)

,Name,Marks
1,Aman,85
2,Neha,90
3,Ravi,78


### Q6. Create `students` with Student_ID, Name, Department and `marks` with Student_ID, Score. Use IDs 101–104 for students and 101,102,103,105 for marks.

**Expected Output: Both DataFrames are created.**

In [ ]:
# Write your answer here
students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Aman', 'Neha', 'Ravi', 'Priya'],
    'Department': ['IT', 'HR', 'IT', 'Sales']
})

marks = pd.DataFrame({
    'Student_ID': [101, 102, 103, 105],
    'Score': [85, 90, 78, 92]
})

print(students, '\n')
print(marks)

   Student_ID   Name Department
0         101   Aman         IT
1         102   Neha         HR
2         103   Ravi         IT
3         104  Priya      Sales 

   Student_ID  Score
0         101     85
1         102     90
2         103     78
3         105     92


### Q7. Perform an **inner merge** of students and marks using `Student_ID`.

**Expected Output: Only IDs 101, 102, 103 remain.**

In [ ]:
# Write your answer here
students.merge(marks, how="inner")

,Student_ID,Name,Department,Score
0,101,Aman,IT,85
1,102,Neha,HR,90
2,103,Ravi,IT,78


### Q8. Perform a **left merge** using `Student_ID`.

**Expected Output: All students remain; ID 104 has missing Score.**

In [ ]:
# Write your answer here
left_mer = students.merge(marks, how='left')

### Q9. Perform a **right merge** using `Student_ID`.

**Expected Output: All marks records remain; ID 105 has missing student information.**

In [ ]:
# Write your answer here
students.merge(marks, how='right')

,Student_ID,Name,Department,Score
0,101,Aman,IT,85
1,102,Neha,HR,90
2,103,Ravi,IT,78
3,105,NaN,NaN,92


### Q10. Perform an **outer merge** using `Student_ID`.

**Expected Output: IDs 101,102,103,104,105 are present.**

In [ ]:
# Write your answer here
out_mer = pd.merge(students, marks, on='Student_ID', how='outer')
out_mer

,Student_ID,Name,Department,Score
0,101,Aman,IT,85.0
1,102,Neha,HR,90.0
2,103,Ravi,IT,78.0
3,104,Priya,Sales,NaN
4,105,NaN,NaN,92.0


### Q11. After the outer merge, use `isnull().sum()` to check missing values.

**Expected Output: Missing values appear for unmatched records.**

In [ ]:
# Write your answer here
out_mer.isnull().sum()

,0
Student_ID,0
Name,1
Department,1
Score,1


### Q12. After the left merge, replace missing Score values with 0 using `fillna()`.

**Expected Output: Student 104 gets Score = 0.**

In [ ]:
# Write your answer here
left_mer.fillna(0)

,Student_ID,Name,Department,Score
0,101,Aman,IT,85.0
1,102,Neha,HR,90.0
2,103,Ravi,IT,78.0
3,104,Priya,Sales,0.0


### Q13. Create `employees` with `Emp_ID, Name` and `salary` with `Employee_ID, Salary`. Use IDs 1,2,3 in employees and 1,2,4 in salary. Merge using `left_on` and `right_on`.

**Expected Output: DataFrames merge using differently named key columns.**

In [ ]:
# Write your answer here
employees = pd.DataFrame({
    "Emp_ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

salary = pd.DataFrame({
    "Employee_ID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

result = pd.merge(
    employees,
    salary,
    left_on="Emp_ID",
    right_on="Employee_ID",
    how="left"
)

print(result)

   Emp_ID     Name  Employee_ID   Salary
0       1    Alice          1.0  50000.0
1       2      Bob          2.0  60000.0
2       3  Charlie          NaN      NaN


### Q14. Using the same employees and salary DataFrames, perform a left merge.

**Expected Output: All employees remain.**

In [ ]:
# Write your answer here
result = pd.merge(
    employees,
    salary,
    left_on="Emp_ID",
    right_on="Employee_ID",
    how="left"
)

print(result)

   Emp_ID     Name  Employee_ID   Salary
0       1    Alice          1.0  50000.0
1       2      Bob          2.0  60000.0
2       3  Charlie          NaN      NaN


### Q15. Create `products` with Product_ID and Product, and `prices` with Product_ID and Price. Set Product_ID as the index in both.

**Expected Output: Product_ID becomes the index in both DataFrames.**

In [ ]:
# Write your answer here
products = pd.DataFrame({
    "Product_ID": [101, 102, 103],
    "Product": ["Laptop", "Phone", "Tablet"]
})

prices = pd.DataFrame({
    "Product_ID": [101, 102, 103],
    "Price": [50000, 30000, 20000]
})

products = products.set_index("Product_ID")
prices = prices.set_index("Product_ID")

print(products)
print(prices)

           Product
Product_ID        
101         Laptop
102          Phone
103         Tablet
            Price
Product_ID       
101         50000
102         30000
103         20000


# ⭐ Bonus Challenge

Create three small DataFrames representing **Employees, Departments, and Salaries**.

- Combine two using `merge()`.
- Add the third using `join()`.
- Use an outer merge.
- Find missing records.
- Finally, explain why the missing values appeared.

**Goal:** Use `concat()`, `merge()`, and `join()` in one mini analysis.

In [ ]:
# Bonus solution
import pandas as pd

# 1. Create Employees DataFrame
employees = pd.DataFrame({
    "Emp_ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

# 2. Create Departments DataFrame
departments = pd.DataFrame({
    "Emp_ID": [1, 2, 4],
    "Department": ["HR", "IT", "Finance"]
})

# 3. Create Salaries DataFrame
salaries = pd.DataFrame({
    "Emp_ID": [1, 2, 3, 5],
    "Salary": [50000, 60000, 55000, 70000]
})


# --- CONCAT ---
# Combine Employees and Departments vertically
concat_result = pd.concat([employees, departments], ignore_index=True)

print("CONCAT RESULT:")
print(concat_result)


# --- OUTER MERGE ---
# Combine Employees and Departments using Emp_ID
merged = pd.merge(
    employees,
    departments,
    on="Emp_ID",
    how="outer"
)

print("\nOUTER MERGE RESULT:")
print(merged)


# --- JOIN ---
# Set Emp_ID as index before joining Salaries
merged_indexed = merged.set_index("Emp_ID")
salaries_indexed = salaries.set_index("Emp_ID")

final_result = merged_indexed.join(salaries_indexed, how="outer")

print("\nFINAL RESULT:")
print(final_result)


# --- FIND MISSING RECORDS ---
print("\nMISSING VALUES:")
print(final_result.isna())

print("\nROWS WITH MISSING VALUES:")
print(final_result[final_result.isna().any(axis=1)])

CONCAT RESULT:
   Emp_ID     Name Department
0       1    Alice        NaN
1       2      Bob        NaN
2       3  Charlie        NaN
3       1      NaN         HR
4       2      NaN         IT
5       4      NaN    Finance

OUTER MERGE RESULT:
   Emp_ID     Name Department
0       1    Alice         HR
1       2      Bob         IT
2       3  Charlie        NaN
3       4      NaN    Finance

FINAL RESULT:
           Name Department   Salary
Emp_ID                             
1         Alice         HR  50000.0
2           Bob         IT  60000.0
3       Charlie        NaN  55000.0
4           NaN    Finance      NaN
5           NaN        NaN  70000.0

MISSING VALUES:
         Name  Department  Salary
Emp_ID                           
1       False       False   False
2       False       False   False
3       False        True   False
4        True       False    True
5        True        True   False

ROWS WITH MISSING VALUES:
           Name Department   Salary
Emp_ID             